name: Validate Detection Rules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Scanner Detection Rules
      uses: sarum90/validate-scanner-detection-rules@v0.2
      with:
        scanner_api_base: '${{ secrets.SCANNER_API_BASE }}'
        scanner_api_key: '${{ secrets.SCANNER_API_KEY }}'
        file_pattern: 'rules/**/*.yml'
